version: 0.0
os: linux
files:
  - source: /
  - destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: deploy-script/after-install.sh
      timeout: 300
  ApplicationStart:
    - location: deploy-script/app-start.sh
      timeout: 100
