version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nodejs
hooks:
  BeforeInstall:
    - location: deploy-script/before-install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deploy-script/after-install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deploy-script/app-start.sh
      timeout: 300
      runas: ec2-user
