version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install typescript -g
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - 'dist/'
    - appspec.yml
    - 'deploy-script/**/*'

