version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install typescript -g
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  paths:
    - '**/*'

